import logging
import pubsub
import order_tasks
import google.cloud.exceptions
from flask import blueprints, request
from google.cloud import firestore

subscription = blueprints.Blueprint('subscription', __name__, url_prefix='/api/subscription')

db = firestore.Client()


@subscription.route('/shopify/test', methods=['POST'])
def shopify_test():
    """
    Triggered by pubsub topic "shopify-test"
    """
    envelope, data = pubsub.decode_data(request.data)

    logging.info(f"{envelope=}")
    logging.info(f"{data=}")

    try:
        webhook_attributes = envelope['message']['attributes']
    except KeyError:
        db.collection("shopifyWebhookNoAttributes").document().set(
            data
        )
        return

    webhook_id = webhook_attributes['X-Shopify-Webhook-Id']
    data['webhook_attributes'] = webhook_attributes

    try:
        db.collection("shopifyWebhook").document(webhook_id).create(
            data
        )
    except google.cloud.exceptions.Conflict:
        logging.info(f"webhook_id already exists: {webhook_id}")
    else:
        order_tasks.process_shopify_webhook(webhook_id=webhook_id)
    # d1 = {'message':
    #     {'attributes':
    #         {
    #             'Content-Type': 'application/json',
    #             'X-Shopify-API-Version': '2022-10',
    #             'X-Shopify-Hmac-SHA256': 'Oxvaeo08b/KT7X1ooSNVEIMHHyzOkC29i7HrMo2FsSA=',
    #             'X-Shopify-Order-Id': '5051921006827',
    #             'X-Shopify-Shop-Domain': 'pink-test-store.myshopify.com',
    #             'X-Shopify-Test': 'true',
    #             'X-Shopify-Topic': 'orders/updated',
    #             'X-Shopify-Webhook-Id': 'cc93edd5-96e7-4adc-89e4-bc6a94d12a19'
    #         },
    #     }
    # }
    #

    # db2 = {'id': 5051921006827,
    #        'admin_graphql_api_id': 'gid://shopify/Order/5051921006827',
    #        'app_id': 580111,
    #        'browser_ip': '86.163.220.26',
    #        'buyer_accepts_marketing': False,
    #        'cancel_reason': None,
    #        'cancelled_at': None,
    #        'cart_token': 'b4977abab1cb444c96e82f1f9cb2d9f0',
    #        'checkout_id': 33359588524267,
    #        'checkout_token': '3e6541f1a329572a9a5a2f35d64d22ad',
    #        'client_details': {'accept_language': 'en-GB,en;q=0.9,en-US;q=0.8',
    #                           'browser_height': 798,
    #                           'browser_ip': '86.163.220.26',
    #                           'browser_width': 1440,
    #                           'session_hash': None,
    #                           'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'},
    #        'closed_at': None,
    #        'confirmed': True,
    #        'contact_email': 'tim.f.barry@gmail.com',
    #        'created_at': '2022-11-27T22:59:53+00:00',
    #        'currency': 'GBP',
    #        'current_subtotal_price': '9.00',
    #        'current_subtotal_price_set': {'shop_money': {'amount': '9.00',
    #                                                      'currency_code': 'GBP'},
    #                                       'presentment_money': {'amount': '9.00',
    #                                                             'currency_code': 'GBP'}},
    #        'current_total_discounts': '0.00',
    #        'current_total_discounts_set': {'shop_money': {'amount': '0.00',
    #                                                       'currency_code': 'GBP'},
    #                                        'presentment_money': {'amount': '0.00',
    #                                                              'currency_code': 'GBP'}},
    #        'current_total_duties_set': None,
    #        'current_total_price': '14.99',
    #        'current_total_price_set': {'shop_money': {'amount': '14.99',
    #                                                   'currency_code': 'GBP'},
    #                                    'presentment_money': {'amount': '14.99',
    #                                                          'currency_code': 'GBP'}},
    #        'current_total_tax': '0.00',
    #        'current_total_tax_set': {'shop_money': {'amount': '0.00',
    #                                                 'currency_code': 'GBP'},
    #                                  'presentment_money': {'amount': '0.00',
    #                                                        'currency_code': 'GBP'}},
    #        'customer_locale': 'en-GB',
    #        'device_id': None,
    #        'discount_codes': [],
    #        'email': 'tim.f.barry@gmail.com',
    #        'estimated_taxes': False,
    #        'financial_status': 'paid',
    #        'fulfillment_status': None,
    #        'gateway': 'bogus',
    #        'landing_site': '/password',
    #        'landing_site_ref': None,
    #        'location_id': None,
    #        'merchant_of_record_app_id': None,
    #        'name': '#1002',
    #        'note': None,
    #        'note_attributes': [],
    #        'number': 2,
    #        'order_number': 1002,
    #        'order_status_url': 'https://pink-test-store.myshopify.com/66633924843/orders/11811672ad4c1f89cae65f9d709b723e/authenticate?key=941a702e44ae74b802f3e3665b99bb5e',
    #        'original_total_duties_set': None,
    #        'payment_gateway_names': ['bogus'],
    #        'phone': None,
    #        'presentment_currency': 'GBP',
    #        'processed_at': '2022-11-27T22:59:52+00:00',
    #        'processing_method': 'direct',
    #        'reference': None,
    #        'referring_site': '',
    #        'source_identifier': None,
    #        'source_name': 'web',
    #        'source_url': None,
    #        'subtotal_price': '9.00',
    #        'subtotal_price_set': {'shop_money': {'amount': '9.00',
    #                                              'currency_code': 'GBP'},
    #                               'presentment_money': {'amount': '9.00',
    #                                                     'currency_code': 'GBP'}},
    #        'tags': '',
    #        'tax_lines': [],
    #        'taxes_included': True,
    #        'test': True,
    #        'token': '11811672ad4c1f89cae65f9d709b723e',
    #        'total_discounts': '0.00',
    #        'total_discounts_set': {'shop_money': {'amount': '0.00',
    #                                               'currency_code': 'GBP'},
    #                                'presentment_money': {'amount': '0.00',
    #                                                      'currency_code': 'GBP'}},
    #        'total_line_items_price': '9.00',
    #        'total_line_items_price_set': {'shop_money': {'amount': '9.00',
    #                                                      'currency_code': 'GBP'},
    #                                       'presentment_money': {'amount': '9.00',
    #                                                             'currency_code': 'GBP'}},
    #        'total_outstanding': '0.00',
    #        'total_price': '14.99',
    #        'total_price_set': {'shop_money': {'amount': '14.99',
    #                                           'currency_code': 'GBP'},
    #                            'presentment_money': {'amount': '14.99',
    #                                                  'currency_code': 'GBP'}},
    #        'total_shipping_price_set': {'shop_money': {'amount': '5.99',
    #                                                    'currency_code': 'GBP'},
    #                                     'presentment_money': {'amount': '5.99',
    #                                                           'currency_code': 'GBP'}},
    #        'total_tax': '0.00',
    #        'total_tax_set': {'shop_money': {'amount': '0.00',
    #                                         'currency_code': 'GBP'},
    #                          'presentment_money': {'amount': '0.00',
    #                                                'currency_code': 'GBP'}},
    #        'total_tip_received': '0.00',
    #        'total_weight': 0,
    #        'updated_at': '2022-11-27T22:59:54+00:00',
    #        'user_id': None,
    #        'billing_address': {'first_name': 'Tim',
    #                            'address1': '2 St. Edwards Walk',
    #                            'phone': None,
    #                            'city': 'CHELTENHAM',
    #                            'zip': 'GL53 7RS',
    #                            'province': 'England',
    #                            'country': 'United Kingdom',
    #                            'last_name': 'Barry',
    #                            'address2': '',
    #                            'company': None,
    #                            'latitude': 51.8870602,
    #                            'longitude': -2.0589523,
    #                            'name': 'Tim Barry',
    #                            'country_code': 'GB',
    #                            'province_code': 'ENG'},
    #        'customer': {'id': 6514317295851,
    #                     'email': 'tim.f.barry@gmail.com',
    #                     'accepts_marketing': False,
    #                     'created_at': '2022-11-25T22:47:11+00:00',
    #                     'updated_at': '2022-11-27T22:59:54+00:00',
    #                     'first_name': 'Tim',
    #                     'last_name': 'Barry',
    #                     'state': 'disabled',
    #                     'note': None,
    #                     'verified_email': True,
    #                     'multipass_identifier': None,
    #                     'tax_exempt': False,
    #                     'tags': '',
    #                     'currency': 'GBP',
    #                     'phone': None,
    #                     'accepts_marketing_updated_at': '2022-11-25T22:47:11+00:00',
    #                     'marketing_opt_in_level': None,
    #                     'tax_exemptions': [],
    #                     'email_marketing_consent': {'state': 'not_subscribed',
    #                                                 'opt_in_level': 'single_opt_in',
    #                                                 'consent_updated_at': None},
    #                     'sms_marketing_consent': None,
    #                     'admin_graphql_api_id': 'gid://shopify/Customer/6514317295851',
    #                     'default_address': {'id': 8095566528747,
    #                                         'customer_id': 6514317295851,
    #                                         'first_name': 'Tim',
    #                                         'last_name': 'Barry',
    #                                         'company': None,
    #                                         'address1': '2 St. Edwards Walk',
    #                                         'address2': '',
    #                                         'city': 'CHELTENHAM',
    #                                         'province': 'England',
    #                                         'country': 'United Kingdom',
    #                                         'zip': 'GL53 7RS',
    #                                         'phone': None,
    #                                         'name': 'Tim Barry',
    #                                         'province_code': 'ENG',
    #                                         'country_code': 'GB',
    #                                         'country_name': 'United Kingdom',
    #                                         'default': True}},
    #        'discount_applications': [],
    #        'fulfillments': [],
    #        'line_items': [{'id': 12849472667883,
    #                        'admin_graphql_api_id': 'gid://shopify/LineItem/12849472667883',
    #                        'fulfillable_quantity': 1,
    #                        'fulfillment_service': 'manual',
    #                        'fulfillment_status': None,
    #                        'gift_card': False,
    #                        'grams': 0,
    #                        'name': 'Postal Product - Postal',
    #                        'price': '9.00',
    #                        'price_set': {'shop_money': {'amount': '9.00',
    #                                                     'currency_code': 'GBP'},
    #                                      'presentment_money': {'amount': '9.00',
    #                                                            'currency_code': 'GBP'}},
    #                        'product_exists': True,
    #                        'product_id': 7864576049387,
    #                        'properties': [],
    #                        'quantity': 1,
    #                        'requires_shipping': True,
    #                        'sku': '',
    #                        'taxable': True,
    #                        'title': 'Postal Product',
    #                        'total_discount': '0.00',
    #                        'total_discount_set': {'shop_money': {'amount': '0.00',
    #                                                              'currency_code': 'GBP'},
    #                                               'presentment_money': {'amount': '0.00',
    #                                                                     'currency_code': 'GBP'}},
    #                        'variant_id': 43412466368747,
    #                        'variant_inventory_management': None,
    #                        'variant_title': 'Postal',
    #                        'vendor': 'pink test store',
    #                        'tax_lines': [],
    #                        'duties': [],
    #                        'discount_allocations': []}],
    #        'payment_details': {'credit_card_bin': '1',
    #                            'avs_result_code': None,
    #                            'cvv_result_code': None,
    #                            'credit_card_number': '•••• •••• •••• 1',
    #                            'credit_card_company': 'Bogus'},
    #        'payment_terms': None,
    #        'refunds': [],
    #        'shipping_address': {'first_name': 'Tim',
    #                             'address1': '2 St. Edwards Walk',
    #                             'phone': None,
    #                             'city': 'CHELTENHAM',
    #                             'zip': 'GL53 7RS',
    #                             'province': 'England',
    #                             'country': 'United Kingdom',
    #                             'last_name': 'Barry',
    #                             'address2': '',
    #                             'company': None,
    #                             'latitude': 51.8870602,
    #                             'longitude': -2.0589523,
    #                             'name': 'Tim Barry',
    #                             'country_code': 'GB',
    #                             'province_code': 'ENG'},
    #        'shipping_lines': [{'id': 4173628342507,
    #                            'carrier_identifier': None,
    #                            'code': 'Standard',
    #                            'delivery_category': None,
    #                            'discounted_price': '5.99',
    #                            'discounted_price_set': {'shop_money': {'amount': '5.99',
    #                                                                    'currency_code': 'GBP'},
    #                                                     'presentment_money': {'amount': '5.99',
    #                                                                           'currency_code': 'GBP'}},
    #                            'phone': None,
    #                            'price': '5.99',
    #                            'price_set': {'shop_money': {'amount': '5.99',
    #                                                         'currency_code': 'GBP'},
    #                                          'presentment_money': {'amount': '5.99',
    #                                                                'currency_code': 'GBP'}},
    #                            'requested_fulfillment_service_id': None,
    #                            'source': 'shopify',
    #                            'title': 'Standard',
    #                            'tax_lines': [],
    #                            'discount_allocations': []}]}

    return "", 204
